openapi: 3.0.3
info:
  title: Kubernetes Service API
  description: |-
    The Kubernetes Service API provides services that allows provisioning and life cycle
    management of Kubernetes clusters. The API is logically composed of authentication
    services, platform provider specific calls to get a set of resource types that can
    be then used by abstract Kubernetes Service resources to create and manage Kubernetes
    clusters. Requests must specify the HTML content type
    header.
  version: 0.2.0
# This allows the documentation engine to combine API endpoints into related groups
# and also defines the order of appearance.
x-documentation-groups:
- id: main
  name: Core API
  description: |-
    The core API allows the management of core resources. Conceptually there are projects
    that are implicitly referenced by a scoped token issued during authentication.  Within
    a project are a number of cluster managers. In the context of the Kubernetes Service, a
    cluster manager is a management layer that provides multi-tenant isolation, and Kubernetes
    cluster provisioning and scaling services. Kubernetes clusters are provisioned within
    a cluster manager. Provisioning of projects and cluster managers may be done explicitly or
    implicitly, however this latter approach is less flexible as the Kubernetes Service will
    have to choose some default values for you, however it provides a faster and better
    user experience.
paths:
  /api/v1/organizations/{organizationName}/projects:
    x-documentation-group: main
    description: |-
      Implements project management services. Projects, as currently defined
      by the Kubernetes service, are implicitly scoped to the access token's
      organization.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    get:
      description: |-
        List all projects for the organization.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/projectsResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    post:
      description: |-
        Creates a new project resource for the user's organization.
      security:
      - oauth2Authentication: []
      requestBody:
        $ref: '#/components/requestBodies/createProjectRequest'
      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '409':
          $ref: '#/components/responses/conflictResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/projects/{projectName}:
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    - $ref: '#/components/parameters/projectNameParameter'
    delete:
      description: |-
        Deletes the project associated with the authenticated user's scoped
        authorisation token. This is a cascading operation and will delete all
        contained cluster managers and clusters.
      security:
      - oauth2Authentication: []
      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/clustermanagers:
    x-documentation-group: main
    description: |-
      Implements cluster manager management services. Control planes manage the
      life cycle of Kubernetes clusters, through provisioning, upgrading, to deletion.
      Control planes must reference a versioned application bundle that defines the
      software versions of cluster manager components, and forms the basis of automatic
      upgrade functionality.  Referencing an explicit cluster manager name will
      implicitly create the associated project.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    get:
      description: |-
        Lists cluster managers within the organization.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/clusterManagersResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/projects/{projectName}/clustermanagers:
    description: |-
      Implements cluster manager management services. Control planes manage the
      life cycle of Kubernetes clusters, through provisioning, upgrading, to deletion.
      Control planes must reference a versioned application bundle that defines the
      software versions of cluster manager components, and forms the basis of automatic
      upgrade functionality.  Referencing an explicit cluster manager name will
      implicitly create the associated project.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    - $ref: '#/components/parameters/projectNameParameter'
    post:
      description: |-
        Creates a new cluster manager within the project.
      security:
      - oauth2Authentication: []
      requestBody:
        $ref: '#/components/requestBodies/createControlPlaneRequest'

      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '409':
          $ref: '#/components/responses/conflictResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/projects/{projectName}/clustermanagers/{clusterManagerName}:
    x-documentation-group: main
    description: |-
      Implements cluster manager management services. Control planes manage the
      life cycle of Kubernetes clusters, through provisioning, upgrading, to deletion.
      Control planes must reference a versioned application bundle that defines the
      software versions of cluster manager components, and forms the basis of automatic
      upgrade functionality.  Referencing an explicit cluster manager name will
      implicitly create the associated project.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    - $ref: '#/components/parameters/projectNameParameter'
    - $ref: '#/components/parameters/clusterManagerNameParameter'
    put:
      description: |-
        Updates a cluster manager within the scoped project.
      security:
      - oauth2Authentication: []
      requestBody:
        $ref: '#/components/requestBodies/createControlPlaneRequest'
      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      description: |-
        Deletes a cluster manager from within the scoped project.
        This is a cascading operation and will delete all contained clusters.
      security:
      - oauth2Authentication: []
      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/clusters:
    x-documentation-group: main
    description: Cluster services.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    get:
      description: |-
        List all clusters within the organization.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/kubernetesClustersResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/projects/{projectName}/clusters:
    x-documentation-group: main
    description: Cluster services.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    - $ref: '#/components/parameters/projectNameParameter'
    post:
      description: |-
        Creates a new cluster within the selected cluster manager.
      security:
      - oauth2Authentication: []
      requestBody:
        $ref: '#/components/requestBodies/createKubernetesClusterRequest'
      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '403':
          $ref: '#/components/responses/forbiddenResponse'
        '409':
          $ref: '#/components/responses/conflictResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/projects/{projectName}/clusters/{clusterName}:
    x-documentation-group: main
    description: Cluster services.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    - $ref: '#/components/parameters/projectNameParameter'
    - $ref: '#/components/parameters/clusterNameParameter'
    put:
      description: |-
        Update a cluster within the selected cluster manager.
      security:
      - oauth2Authentication: []
      requestBody:
        $ref: '#/components/requestBodies/createKubernetesClusterRequest'
      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      description: |-
        Delete a cluster from within a the selected cluster manager.
      security:
      - oauth2Authentication: []
      responses:
        '202':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/organizations/{organizationName}/projects/{projectName}/clusters/{clusterName}/kubeconfig:
    x-documentation-group: main
    description: Cluster services.
    parameters:
    - $ref: '#/components/parameters/organizationNameParameter'
    - $ref: '#/components/parameters/projectNameParameter'
    - $ref: '#/components/parameters/clusterNameParameter'
    get:
      description: |-
        Get a cluster's Kubernetes configuration.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/kubernetesClusterKubeconfigResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/applications:
    x-documentation-group: main
    description: Cluster application services.
    get:
      description: |-
        Lists applications available to be installed on clusters.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/applicationResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/regions:
    description: |-
      Regions define a cloud.  This may be geographical or any logical partition.
      Either way this is the primitive that is used to associate metadata such as
      geographical locale, an organisation's reserved blob of compute etc.
      Each region has its own provider associated with it, for example OpenStack, and
      its own set of credentials so things can be scoped to a specific slice of a
      shared cloud through whatever mechanism is available on that cloud provider.
    get:
      description: |-
        List all regions.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/regionsResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/regions/{regionName}/flavors:
    description: Compute flavor services.
    parameters:
    - $ref: '#/components/parameters/regionNameParameter'
    get:
      description: |-
        Lists all compute flavors that the authenticated user has access to
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/flavorsResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/regions/{regionName}/images:
    description: Compute image services.
    parameters:
    - $ref: '#/components/parameters/regionNameParameter'
    get:
      description: |-
        Lists all compute images that the authenticated user has access to.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/imagesResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  parameters:
    organizationNameParameter:
      name: organizationName
      in: path
      description: |-
        The organization name.
      required: true
      schema:
        $ref: '#/components/schemas/kubernetesNameParameter'
    projectNameParameter:
      name: projectName
      in: path
      description: |-
        The project name.
      required: true
      schema:
        $ref: '#/components/schemas/kubernetesNameParameter'
    clusterManagerNameParameter:
      name: clusterManagerName
      in: path
      description: |-
        The cluster manager name, if the cluster manager does not exist, then it may be
        implicitly created, for example a cluster is created against a cluster manager
        that does not exist. Must be a valid DNS containing only lower case characters,
        numbers or hyphens, start and end with a character or number, and be at most
        63 characters in length.
      required: true
      schema:
        $ref: '#/components/schemas/kubernetesNameParameter'
    clusterNameParameter:
      name: clusterName
      in: path
      description: |-
        The cluster name. Must be a valid DNS containing only lower case characters,
        numbers or hyphens, start and end with a character or number, and be at most
        63 characters in length.
      required: true
      schema:
        $ref: '#/components/schemas/kubernetesNameParameter'
    regionNameParameter:
      name: regionName
      in: path
      description: |-
        The region name.
      required: true
      schema:
        $ref: '#/components/schemas/kubernetesNameParameter'
  schemas:
    kubernetesNameParameter:
      description: A Kubernetes name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
      type: string
      minLength: 1
      maxLength: 63
    oauth2Error:
      description: Generic error message.
      type: object
      required:
      - error
      - error_description
      properties:
        error:
          description: A terse error string expanding on the HTTP error code. Errors are based on the OAuth2 specification, but are expanded with proprietary status codes for APIs other than those specified by OAuth2.
          type: string
          enum:
          # Defined by OAuth2
          - invalid_request
          - unauthorized_client
          - access_denied
          - unsupported_response_type
          - invalid_scope
          - server_error
          - temporarily_unavailable
          - invalid_client
          - invalid_grant
          - unsupported_grant_type
          # Proprietary
          - not_found
          - conflict
          - method_not_allowed
          - unsupported_media_type
          - forbidden
        error_description:
          description: Verbose message describing the error.
          type: string
    resourceMetadata:
      description: A resources's metadata
      type: object
      required:
      - creationTime
      - status
      properties:
        project:
          description: Where the resource is related to a project, this is populated.
          type: string
        clustermanager:
          description: Where the resource is scoped to a cluster manager, this is populated.
          type: string
        region:
          description: Where the resource is scoped to a region, this is populated,
          type: string
        creationTime:
          description: The time the resource was created.
          type: string
          format: date-time
        deletionTime:
          description: The time the resource was deleted.
          type: string
          format: date-time
        status:
          description: |-
            The current status of the resource. Intially the status will be "Unknown" until
            the resource is reconciled by the relevant controller. It then will transition to
            "Provisioning" and will be ready for use when it changes to "Provisioned". The status
            will also transition to the "Provisioning" status during an update. The
            status will change to "Deprovisioning" when a delete request is being processed.
            It may also change to "Error" if an unexpected error occurred during any operation.
            Errors may be transient.
          type: string
    region:
      description: A region.
      type: object
      required:
      - name
      properties:
        name:
          description: The region name.
          type: string
    regions:
      description: A list of regions.
      type: array
      items:
        $ref: '#/components/schemas/region'
    project:
      description: A project.
      type: object
      required:
      - name
      properties:
        metadata:
          $ref: '#/components/schemas/resourceMetadata'
        name:
          type: string
    projects:
      description: A list of projects.
      type: array
      items:
        $ref: '#/components/schemas/project'
    clusterManager:
      description: A cluster manager.
      type: object
      required:
      - name
      properties:
        metadata:
          $ref: '#/components/schemas/resourceMetadata'
        name:
          description: The name of the resource.
          type: string
    clusterManagers:
      description: A list of cluster managers.
      type: array
      items:
        $ref: '#/components/schemas/clusterManager'
    kubernetesClusterNetwork:
      description: A kubernetes cluster network settings.
      type: object
      properties:
        nodePrefix:
          description: Network prefix to provision nodes in. Must be a valid CIDR block.
          type: string
        servicePrefix:
          description: Network prefix to provision services in. Must be a valid CIDR block.
          type: string
        podPrefix:
          description: Network prefix to provision pods in. Must be a valid CIDR block.
          type: string
        dnsNameservers:
          description: A list of DNS name server to use.
          type: array
          items:
            description: A DNS nameserver IPv4 address.
            type: string
    kubernetesClusterAPI:
      description: Kubernetes API settings.
      type: object
      properties:
        subjectAlternativeNames:
          description: Set of non-standard X.509 SANs to add to the API certificate.
          type: array
          minItems: 1
          items:
            description: An X.509 SAN.
            type: string
        allowedPrefixes:
          description: Set of address prefixes to allow access to the Kubernetes API.
          type: array
          minItems: 1
          items:
            description: An IPv4 CIDR address prefix.
            type: string
    volume:
      description: A volume.
      type: object
      required:
      - size
      properties:
        size:
          description: Disk size in GiB.
          type: integer
    machinePool:
      description: A Kubernetes cluster machine.
      type: object
      properties:
        replicas:
          description: Number of machines for a statically sized pool or the maximum
            for an auto-scaled pool.
          type: integer
        flavorName:
          description: Flavor name.
          type: string
          minLength: 1
        disk:
          $ref: '#/components/schemas/volume'
    kubernetesClusterAutoscaling:
      description: |-
        A Kubernetes cluster workload pool autoscaling configuration. Cluster autoscaling
        must also be enabled in the cluster features.
      type: object
      required:
      - minimumReplicas
      properties:
        minimumReplicas:
          description: |-
            The minimum number of replicas to allow. Must be less than the maximum.
          type: integer
    kubernetesClusterWorkloadPool:
      description: A Kuberntes cluster workload pool.
      type: object
      required:
      - name
      - machine
      properties:
        name:
          description: Workload pool name.
          type: string
        machine:
          $ref: '#/components/schemas/machinePool'
        labels:
          description: Workload pool key value labels to apply on node creation.
          type: object
          additionalProperties:
            description: A string value.
            type: string
        autoscaling:
          $ref: '#/components/schemas/kubernetesClusterAutoscaling'
    kubernetesClusterWorkloadPools:
      description: A list of Kubernetes cluster workload pools.
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/kubernetesClusterWorkloadPool'
    kubernetesCluster:
      description: Kubernetes cluster creation parameters.
      type: object
      required:
      - name
      - region
      - version
      - workloadPools
      properties:
        metadata:
          $ref: '#/components/schemas/resourceMetadata'
        name:
          description: Cluster name.
          type: string
        region:
          description: The region to provision the cluster in.
          type: string
        clusterManager:
          description: |-
            The name of the cluster manager to use, if one is not specified
            the system will create one for you.
          type: string
        version:
          description: The Kuebernetes version.  This should be derived from
            image metadata.
          type: string
        workloadPools:
          $ref: '#/components/schemas/kubernetesClusterWorkloadPools'
    kubernetesClusters:
      description: A list of Kubernetes clusters.
      type: array
      items:
        $ref: '#/components/schemas/kubernetesCluster'
    applicationVersion:
      description: An application version.
      type: object
      required:
      - version
      properties:
        version:
          description: The application's Helm chart version.
          type: string
        dependencies:
          $ref: '#/components/schemas/applicationDependencies'
        recommends:
          $ref: '#/components/schemas/applicationRecommends'
    applicationVersions:
      description: A set of application versions.
      type: array
      items:
        $ref: '#/components/schemas/applicationVersion'
    applicationTags:
      description: A set of tags for filtering applications.
      type: array
      items:
        description: An application tag.
        type: string
    applicationDependency:
      description: An application dependency.
      type: object
      required:
      - name
      properties:
        name:
          description: The application name.
          type: string
    applicationDependencies:
      description: A set of applications that will be installed before this application.
      type: array
      items:
        $ref: '#/components/schemas/applicationDependency'
    applicationRecommends:
      description: A set of recommended application that may be installed after this application.
      type: array
      items:
        $ref: '#/components/schemas/applicationDependency'
    application:
      description: An application.
      type: object
      required:
      - name
      - humanReadableName
      - description
      - documentation
      - license
      - icon
      - versions
      properties:
        name:
          description: Unique application name.
          type: string
        humanReadableName:
          description: Human readable application name.
          type: string
        description:
          description: Verbose description of what the application provides.
          type: string
        documentation:
          description: Documentation link for the application.
          type: string
          format: uri
        license:
          description: The license under which the application is released.
          type: string
        icon:
          description: A base64 encoded SVG icon.  This should work in both light and dark themes.
          type: string
          format: byte
        versions:
          $ref: '#/components/schemas/applicationVersions'
        tags:
          $ref: '#/components/schemas/applicationTags'
    applications:
      description: A list of appications.
      type: array
      items:
        $ref: '#/components/schemas/application'
    imageVersions:
      description: Image version metadata.
      type: object
      required:
      - kubernetes
      - nvidiaDriver
      properties:
        kubernetes:
          description: |-
            The kubernetes semantic version.  This should be used directly when specifying
            Kubernetes cluster managers and workload pools in a cluster specification.
          type: string
        nvidiaDriver:
          description: The nvidia driver version.
          type: string
    image:
      description: An image.
      type: object
      required:
      - id
      - name
      - created
      - modified
      - versions
      properties:
        id:
          description: The unique image ID.
          type: string
        name:
          description: The image name.
          type: string
        created:
          description: |-
            Time when the image was created. Images with a newer creation time should
            be favoured over older images as they will contain updates and fewer vulnerabilities.
          type: string
          format: date-time
        modified:
          description: Time when the image was last modified.
          type: string
          format: date-time
        versions:
          $ref: '#/components/schemas/imageVersions'
    images:
      description: A list of images that are compatible with this platform.
      type: array
      items:
        $ref: '#/components/schemas/image'
    flavor:
      description: A flavor.
      type: object
      required:
      - id
      - name
      - cpus
      - memory
      - disk
      properties:
        id:
          description: The unique flavor ID.
          type: string
        name:
          description: The flavor name.
          type: string
        cpus:
          description: The number of CPUs.
          type: integer
        memory:
          description: The amount of memory in GiB.
          type: integer
        disk:
          description: The amount of ephemeral disk in GB.
          type: integer
        gpus:
          description: The number of GPUs, if not set there are none.
          type: integer
    flavors:
      description: A list of flavors.
      type: array
      items:
        $ref: '#/components/schemas/flavor'
  requestBodies:
    createProjectRequest:
      description: Project request parameters.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/project'
          example:
            name: my-project
    createControlPlaneRequest:
      description: Control plane request parameters.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/clusterManager'
          example:
            name: default
    createKubernetesClusterRequest:
      description: Kubernetes cluster request parameters.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/kubernetesCluster'
          example:
            region: uk-east-1
            version: v1.27.2
            name: cluster
            workloadPools:
            - autoscaling:
                minimumReplicas: 0
              machine:
                flavorName: g.4.highmem.a100.1g.10gb
                replicas: 3
              name: default
  responses:
    acceptedResponse:
      description: |-
        The request has been accepted and will be fulfilled asynchronously.
        You may poll the resource and monitor its status for completion.
    badRequestResponse:
      description: |-
        Request body failed schema validation, or the request does not contain
        all the required fields.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
          example:
            error: invalid_request
            error_description: request body invalid
    unauthorizedResponse:
      description: |-
        Authentication failed or the access token has expired.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
          example:
            error: access_denied
            error_description: authentication failed
    forbiddenResponse:
      description: |-
        Request was denied by authorisation, this may be caused by the authorisation
        token not having the required scope for an API, or the user doesn't have the
        necessary privileges on the provider platform.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
          example:
            error: forbidden
            error_description: user credentials do not have the required privileges
    notFoundResponse:
      description: |-
        Unable to find a resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
          example:
            error: not_found
            error_description: the requested resource does not exist
    conflictResponse:
      description: |-
        Resource conflicts with another, usually this means they have the same name.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
          example:
            error: conflict
            error_description: a resource with the same name already exists
    internalServerErrorResponse:
      description: |-
        An unexpected error occurred, this may be an unexpected transient error and
        may succeed on a retry. If this isn't the case, please report it as an issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
          example:
            error: server_error
            error_description: failed to token claim
    regionsResponse:
      description: A list of regions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/regions'
          example:
          - name: uk-west
          - name: uk-east
    projectsResponse:
      description: A list of projects.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/projects'
          example:
          - name: my-project
    clusterManagerResponse:
      description: A cluster manager.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/clusterManager'
          example:
            name: default
            status:
              creationTime: 2023-07-31T10:45:42Z
              name: default
              status: Provisioned
    clusterManagersResponse:
      description: A list of cluster managers.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/clusterManagers'
          example:
          - name: default
            status:
              creationTime: 2023-07-31T10:45:42Z
              name: default
              status: Provisioned
    kubernetesClusterKubeconfigResponse:
      description: A Kubernetes cluster configuration.
      content:
        application/octet-stream: {}
    kubernetesClustersResponse:
      description: A list of Kubernetes clusters.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/kubernetesClusters'
          example:
          - name: cluster
            region: uk-east-1
            version: v1.27.2
            status:
              creationTime: 2023-07-31T10:45:45Z
              name: cluster
              status: Provisioned
            workloadPools:
            - name: default
              machine:
                disk:
                  size: 50
                flavorName: g.4.highmem.a100.1g.10gb
                replicas: 3
    applicationResponse:
      description: A list of available applications.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/applications'
          example:
          - description: |-
              Provides an alternative replicated storage provider that distributes storage across
              the Kubernetes cluster.  Features high-availabilty, incremental snapshots and backups,
              disaster recovery, and shared file mounts (read/write many).
            documentation: https://longhorn.io/
            humanReadableName: Longhorn
            icon: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTQuMjU2MTkgMTU5LjA4OTEyIj48dGl0bGU+aWNvbjwvdGl0bGU+PHBhdGggZmlsbD0iIzVmMjI0YSIgZD0iTTk3LjEyODEsODAuNjI2OWExMC4wMDksMTAuMDA5LDAsMCwxLTEuOTU4LS4xOTMzNmwtNS4yODM5NC0xLjA1NDkzLDQuNTQ4NTksMjcuOTgzMTVhOS45MjQyOSw5LjkyNDI5LDAsMCwxLC4xMjk4OCwxLjYwNDQ5aDUuMTI2YTkuOTk5Nyw5Ljk5OTcsMCwwLDEsLjE2MzA4LTEuNzk3MzZsNS4wOTgxNS0yNy45MDY0M0w5OS4wODYxLDgwLjQzMzU0QTEwLjAwODkyLDEwLjAwODkyLDAsMCwxLDk3LjEyODEsODAuNjI2OVoiLz48cGF0aCBmaWxsPSIjNWYyMjRhIiBkPSJNMTczLjY5NTYsMEgyMC41NjA3MUEyMC42MjEwNSwyMC42MjEwNSwwLDAsMCwwLDIwLjU2MDY3VjEzOC41Mjg0NWEyMC42MjEwNiwyMC42MjEwNiwwLDAsMCwyMC41NjA2NywyMC41NjA2N0gxNzMuNjk1NmEyMC42MjEsMjAuNjIxLDAsMCwwLDIwLjU2MDU1LTIwLjU2MDY3VjIwLjU2MDY3QTIwLjYyMSwyMC42MjEsMCwwLDAsMTczLjY5NTYsMFptMy40NTUsNDEuNTgxLTIuNTAyLDE3YTEwLjAwMDYsMTAuMDAwNiwwLDAsMS03LjkzNTU0LDguMzUwNThMMTI2LjA0NTQ1LDc1LjA1MWMtLjAwNy4wNDA3MS0uMDA4NTQuMDgxMDYtLjAxNi4xMjE3N2wtNi4zNjYyMSwzNC44NTA1OEEyMC4wMjY1LDIwLjAyNjUsMCwwLDEsOTkuNjkwNiwxMjguOTY2MjVoLTUuMTI2YTIwLjAyNTg3LDIwLjAyNTg3LDAsMCwxLTE5Ljk3ODUyLTE5LjA1ODFMNjguOTQ0NzUsNzUuMTk3NThsLTQxLjQwMTYyLTguMjY2QTEwLjAwMDYsMTAuMDAwNiwwLDAsMSwxOS42MDc1OSw1OC41ODFsLTIuNTAyLTE3YTEwLjAwMDEzLDEwLjAwMDEzLDAsMCwxLDE5Ljc4NzExLTIuOTEyMTFsMS40NzU1OSwxMC4wMjkzTDk3LjEyODEsNjAuNDI5NjNsNTguNzU5NzYtMTEuNzMxNDQsMS40NzU1OS0xMC4wMjkzQTEwLjAwMDEzLDEwLjAwMDEzLDAsMCwxLDE3Ny4xNTA1Niw0MS41ODFaIi8+PC9zdmc+Cg==
            license: Apache-2.0 License
            name: longhorn-1.5.1-1
            versions:
            - version: 1.5.1
    imagesResponse:
      description: A list of images that are compatible with this platform.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/images'
          example:
          - created: 2023-02-22T12:04:13Z
            id: a64f9269-36e0-4312-b8d1-52d93d569b7b
            modified: 2023-02-22T12:15:18Z
            name: ubu2204-v1.25.6-gpu-525.85.05-7ced4154
            versions:
              kubernetes: v1.25.6
              nvidiaDriver: 525.85.05
    flavorsResponse:
      description: A list of flavors.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/flavors'
          example:
          - cpus: 4
            disk: 20
            gpus: 1
            id: 9a8c6370-4065-4d4a-9da0-7678df40cd9d
            memory: 32
            name: g.4.highmem.a100.1g.10gb
  securitySchemes:
    oauth2Authentication:
      description: Operation requires OAuth2 bearer token authentication.
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://identity.unikorn-cloud.org/oauth2/v2/authorization
          tokenUrl: https://identity.unikorn-cloud.org/oauth2/v2/token
          scopes: {}
